### ISSUE TITLE
回车重复上次命令

### ISSUE THREAD

**Issue by lymslive** [cpiger/NeoDebug#1]
在原生 gdb 中，执行一次 n 命令后，直接按回车重复上次命令，这比按 <F10> 或 <F11> 方便

**Comment by cpiger** [comment]
[feature add: support <enter> to repeat last gdb command.](https://github.com/cpiger/NeoDebug/commit/1fc1caab83bb4b1ecb8057b72303b2e9c37b3454)

**Comment by cpiger** [comment]
[feature add: support <enter> to repeat last gdb command.](https://github.com/cpiger/NeoDebug/commit/1fc1caab83bb4b1ecb8057b72303b2e9c37b3454)
