### ISSUE TITLE
How to get stdout

### ISSUE THREAD

**Issue by izhengfan** [cpiger/NeoDebug#3]
In original gdb the the stdout is directly printed in the gdb console, but it seems to be suppressed in NeoDebug. How can we get it back?

**Comment by cpiger** [comment]
You can use  'tty' command to  redirected program's  input and output on linux.
A similar command under Windows is set new-console, that is default on NeoDebug.

**Comment by cpiger** [comment]
[4.6 Your Program’s Input and Output](https://sourceware.org/gdb/onlinedocs/gdb/Input_002fOutput.html)

**Comment by izhengfan** [comment]
Got it, thanks.
