### ISSUE TITLE
能否加一个新窗口：可以增加表达式，每条gdb命令后刷新他们的值？

### ISSUE THREAD

**Issue by skywind3000** [cpiger/NeoDebug#4]
我想监控一些全局变量，或者表达式，相当于每条gdb命令结束后，帮我 print 一下他们的值，当然是以GUI的形式显示出来的。

**Comment by skywind3000** [comment]
这个功能 [gdbgui](https://github.com/cs01/gdbgui) 做的很好：

![gdbgui](https://user-images.githubusercontent.com/3035071/39704603-6effcf4c-523e-11e8-8ced-c80258bd5a3d.jpg)

当然不用那么复杂，值显示的话，简单一行字就行，要看复杂的我自己 gdb 命令里 print，但是这样已经很有用了。

**Comment by cpiger** [comment]
已经加好了，欢迎测试。 OpenExpressions  CloseExpressions

**Comment by skywind3000** [comment]
多谢啊，另外是能不能有个选项，enable后就跳过默认keymap设置？我的f1-f12都用满了，我想自己定制keymap

**Comment by cpiger** [comment]
Keymaps:

let g:neodbg_keymap_toggle_breakpoint  = '<F9>'         " toggle breakpoint on current line
let g:neodbg_keymap_next               = '<F10>'        " next
let g:neodbg_keymap_run_to_cursor      = '<C-F10>'      " run to cursor (tb and c)
let g:neodbg_keymap_jump               = '<C-S-F10>'    " set next statement (tb and jump)
let g:neodbg_keymap_step_into          = '<F11>'        " step into
let g:neodbg_keymap_step_out           = '<S-F11>'      " setp out
let g:neodbg_keymap_continue           = '<F5>'         " run or continue
let g:neodbg_keymap_print_variable     = '<C-P>'        " view variable under the cursor
let g:neodbg_keymap_stop_debugging     = '<S-F5>'       " stop debugging (kill)
let g:neodbg_keymap_toggle_console_win = '<F6>'         " toggle console window
let g:neodbg_keymap_terminate_debugger = '<C-C>'        " terminate debugger

**Comment by skywind3000** [comment]
谢谢，这项目还继续维护么？
